# Generated by Django 5.2.6 on 2025-09-14 21:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='miniproject',
            name='deployment_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='miniproject',
            name='github_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='miniproject',
            name='report',
            field=models.FileField(blank=True, null=True, upload_to='reports/'),
        ),
        migrations.RemoveField(
            model_name='miniproject',
            name='assigned_to',
        ),
        migrations.AddField(
            model_name='miniproject',
            name='assigned_to',
            field=models.ManyToManyField(related_name='mini_projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
