# Generated by Django 5.2.6 on 2025-09-14 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_miniproject_deployment_link_miniproject_github_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='miniproject',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
