# Generated by Django 5.2.6 on 2025-09-14 22:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_miniproject_completed_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='miniproject',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='miniproject',
            name='deployment_link',
        ),
        migrations.RemoveField(
            model_name='miniproject',
            name='github_link',
        ),
        migrations.RemoveField(
            model_name='miniproject',
            name='report',
        ),
        migrations.RemoveField(
            model_name='miniproject',
            name='status',
        ),
        migrations.CreateModel(
            name='TraineeProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('todo', 'To Do'), ('inprogress', 'In Progress'), ('complete', 'Complete')], default='todo', max_length=20)),
                ('report', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('deployment_link', models.URLField(blank=True, null=True)),
                ('github_link', models.URLField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_entries', to='tracker.miniproject')),
                ('trainee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('trainee', 'project')},
            },
        ),
    ]
