# Generated by Django 5.2.6 on 2025-09-15 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_remove_miniproject_completed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='traineeprogress',
            name='trainer_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
